### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [closedcube/ClosedCube_OPT3001_Arduino#2]
In the file "ClosedCube_OPT3001.cpp" there is no need to wait after Wire.requestFrom(). See https://github.com/closedcube/ClosedCube_SHT31D_Arduino/issues/2

**Comment by closedcube** [comment]
Please see our reply.

**Comment by Koepel** [comment]
Keeping the (minor) bug and closing this issue is not a good idea.

**Comment by closedcube** [comment]
Please see our response
