### ISSUE TITLE
Getting error as response every time

### ISSUE THREAD

**Issue by microcontrollershub** [closedcube/ClosedCube_OPT3001_Arduino#3]
Hello there..
Thanks for writing such a beautiful piece of code.

For me it seems to be working, but in void loop(), while reading sensor data register 00H, I am always getting error response.

I tried changing register value 00H to FFH and I was successful in reading device ID. This proves there is no problem in hardware side.

Please help me, and let me know if I am missing anything !!

**Comment by closedcube** [comment]
Hello,

Please let us know an error code while reading data from the sensor.
